### ISSUE TITLE
[Release Testing] 1-15 : 미리 정해진 ID/PW로만 접근 가능

### ISSUE THREAD

**Issue by usageness** [SEProject5/Client#12]
### Expected behavior
일반적인 회원가입으로 생성한 id는 관리자 페이지에 접근할 수 없음.

### Actual behavior
도메인 창에 /admin 을 입력하게 되면 일반적인 유저 아이디로도 접근 및 기능 이용 가능.

**Comment by highcastlee** [comment]
1-15 해결
