### ISSUE TITLE
[Release Testing] 1-30 : 삭제를 선택하면 상품이 삭제되었다고 표시되어야 함 - 실제 삭제는 하지 않음.

### ISSUE THREAD

**Issue by usageness** [SEProject5/Client#13]
### Expected behavior
상품 삭제시 비활성화 상태로 변경 (실제 삭제는 되지 않음)

### Actual behavior
상품 삭제시 리스트에서 사라져 실제 삭제 여부를 확인 불가능

**Comment by highcastlee** [comment]
1-30 해결
