### ISSUE TITLE
[Release Testing] 2-7 : 2-4, 2-5, 2-6의 기능을 동시에 적용할 수 있어야 함

### ISSUE THREAD

**Issue by usageness** [SEProject5/Client#17]
### Expected behavior
2-4, 2-5, 2-6 기능을 동시 적용하여 필터에 해당하는 상품만 확인 가능.

### Actual behavior
가격대 필터 기능이 정상적으로 동작하지 않음.

**Comment by highcastlee** [comment]
2-7 해결
